import { StyleSheet } from 'react-native'

import { colors } from '@/theme/colors'

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { paddingHorizontal: 18, paddingBottom: 100 },
  headerContent: { paddingTop: 28, paddingBottom: 16, gap: 8 },
  eyebrow: { color: colors.primary, fontSize: 11, fontWeight: '800', letterSpacing: 2 },
  heading: { color: colors.text, fontSize: 30, fontWeight: '800' },
  subheading: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  filters: {
    backgroundColor: colors.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 15,
    gap: 12,
    marginTop: 16,
  },
  searchBox: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
  },
  searchInput: { flex: 1, fontSize: 14, color: colors.text },
  count: { color: colors.text, fontWeight: '700', fontSize: 14, marginTop: 16 },
  separator: { height: 12 },
  empty: { color: colors.muted, textAlign: 'center', paddingVertical: 48 },
  listState: { alignItems: 'center', gap: 8, paddingVertical: 36 },
  retryButton: {
    borderRadius: 11,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  retryText: { color: colors.white, fontWeight: '700', fontSize: 13 },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 20,
  },
  pageButton: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  pageButtonDisabled: { opacity: 0.45 },
  pageButtonText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  pageLabel: { color: colors.muted, fontSize: 12 },
  floatingButton: {
    position: 'absolute',
    right: 18,
    bottom: 26,
    backgroundColor: colors.primary,
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    elevation: 7,
  },
  floatingText: { color: colors.white, fontWeight: '700', fontSize: 15 },
})
