import { randomUUID } from 'node:crypto'

import type { Knex } from 'knex'

export async function seed(knex: Knex): Promise<void> {
  await knex('ticket_activities').delete()
  await knex('tickets').delete()

  const openTicketId = randomUUID()
  const triageTicketId = randomUUID()
  const inProgressTicketId = randomUUID()
  const resolvedTicketId = randomUUID()
  const closedTicketId = randomUUID()

  const now = new Date().toISOString()

  await knex('tickets').insert([
    {
      idticket: openTicketId,
      titulo: 'Solicitação de acesso ao sistema financeiro',
      descricao: 'O usuário precisa de acesso ao sistema financeiro para consultar relatórios.',
      categoria: 'Access',
      prioridade: 'medium',
      status: 'open',
      solicitante: 'Mariana Costa',
      responsavel: null,
      tipoResolucao: null,
      resumoResolucao: null,
      resolvedAt: null,
      closedAt: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idticket: triageTicketId,
      titulo: 'Notebook reiniciando durante o expediente',
      descricao: 'O notebook reinicia sozinho durante o uso e interrompe as atividades do usuário.',
      categoria: 'Hardware',
      prioridade: 'high',
      status: 'triage',
      solicitante: 'Carlos Almeida',
      responsavel: null,
      tipoResolucao: null,
      resumoResolucao: null,
      resolvedAt: null,
      closedAt: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idticket: inProgressTicketId,
      titulo: 'Sistema comercial apresenta lentidão',
      descricao: 'O sistema comercial demora para carregar clientes e salvar novos pedidos.',
      categoria: 'Software',
      prioridade: 'critical',
      status: 'in_progress',
      solicitante: 'Fernanda Lima',
      responsavel: 'Lucas Martins',
      tipoResolucao: null,
      resumoResolucao: null,
      resolvedAt: null,
      closedAt: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idticket: resolvedTicketId,
      titulo: 'Falha de conexão com a rede interna',
      descricao: 'O computador não conseguia acessar os serviços disponíveis na rede interna.',
      categoria: 'Network',
      prioridade: 'high',
      status: 'resolved',
      solicitante: 'Rafael Souza',
      responsavel: 'Ana Ribeiro',
      tipoResolucao: 'fixed',
      resumoResolucao: 'O cabo de rede defeituoso foi substituído e a conexão foi restabelecida.',
      resolvedAt: now,
      closedAt: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idticket: closedTicketId,
      titulo: 'Alerta de segurança no correio eletrônico',
      descricao:
        'O usuário recebeu uma mensagem suspeita solicitando suas credenciais corporativas.',
      categoria: 'Security',
      prioridade: 'critical',
      status: 'closed',
      solicitante: 'Juliana Mendes',
      responsavel: 'Pedro Rocha',
      tipoResolucao: 'no_issue',
      resumoResolucao:
        'A mensagem foi analisada, removida e o remetente foi bloqueado no servidor.',
      resolvedAt: now,
      closedAt: now,
      createdAt: now,
      updatedAt: now,
    },
  ])

  await knex('ticket_activities').insert([
    {
      idactivity: randomUUID(),
      idticket: openTicketId,
      tipo: 'comment',
      descricao: 'Solicitação recebida e aguardando análise da equipe responsável.',
      autor: 'Gabriel',
      tempoGastoMinutos: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: triageTicketId,
      tipo: 'comment',
      descricao: 'O usuário informou que as reinicializações começaram nesta manhã.',
      autor: 'Carlos',
      tempoGastoMinutos: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: inProgressTicketId,
      tipo: 'comment',
      descricao: 'A lentidão ocorre principalmente durante o cadastro de pedidos.',
      autor: 'Fernanda',
      tempoGastoMinutos: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: closedTicketId,
      tipo: 'comment',
      descricao: 'O usuário confirmou que não informou suas credenciais na mensagem.',
      autor: 'Juliana',
      tempoGastoMinutos: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: triageTicketId,
      tipo: 'diagnosis',
      descricao: 'Foram encontrados registros de superaquecimento durante o uso do equipamento.',
      autor: 'Beatriz',
      tempoGastoMinutos: 25,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: inProgressTicketId,
      tipo: 'diagnosis',
      descricao: 'A consulta de pedidos apresenta tempo de resposta acima do esperado.',
      autor: 'Lucas',
      tempoGastoMinutos: 40,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: resolvedTicketId,
      tipo: 'diagnosis',
      descricao: 'O teste identificou perda de pacotes causada por um cabo de rede danificado.',
      autor: 'Ana',
      tempoGastoMinutos: 20,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: openTicketId,
      tipo: 'action',
      descricao: 'O pedido de acesso foi encaminhado para aprovação do gestor responsável.',
      autor: 'Gabriel',
      tempoGastoMinutos: 10,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: triageTicketId,
      tipo: 'action',
      descricao: 'Foi agendada uma avaliação presencial do notebook com a equipe técnica.',
      autor: 'Beatriz',
      tempoGastoMinutos: 15,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: inProgressTicketId,
      tipo: 'action',
      descricao: 'A equipe iniciou a otimização da consulta utilizada no cadastro de pedidos.',
      autor: 'Lucas',
      tempoGastoMinutos: 60,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: resolvedTicketId,
      tipo: 'action',
      descricao: 'O cabo defeituoso foi substituído e a conectividade foi testada com sucesso.',
      autor: 'Ana',
      tempoGastoMinutos: 30,
      createdAt: now,
      updatedAt: now,
    },
    {
      idactivity: randomUUID(),
      idticket: closedTicketId,
      tipo: 'action',
      descricao: 'A mensagem foi removida e o remetente bloqueado no servidor de e-mail.',
      autor: 'Pedro',
      tempoGastoMinutos: 35,
      createdAt: now,
      updatedAt: now,
    },
  ])
}
