import { StyleSheet } from 'react-native'

import { colors } from '@/theme/colors'

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 18, paddingBottom: 40, gap: 16 },
  back: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10 },
  backText: { color: colors.primary, fontSize: 14, fontWeight: '700' },
  titleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  titleGroup: { flex: 1, gap: 6 },
  code: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  title: { color: colors.text, fontWeight: '800', fontSize: 25, lineHeight: 30 },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    padding: 10,
    borderRadius: 10,
    borderColor: colors.border,
    borderWidth: 1,
    backgroundColor: colors.white,
  },
  editText: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  badges: { flexDirection: 'row', gap: 8 },
  card: {
    backgroundColor: colors.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    gap: 14,
  },
  sectionTitle: { color: colors.text, fontSize: 17, fontWeight: '700' },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 20 },
  detailLabel: { color: colors.muted, fontSize: 13 },
  detailValue: { color: colors.text, fontSize: 13, fontWeight: '600', flex: 1, textAlign: 'right' },
  descriptionLabel: {
    color: colors.muted,
    fontSize: 13,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 14,
  },
  description: { color: colors.text, fontSize: 14, lineHeight: 21 },
  activitiesTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  activitiesCount: { color: colors.muted, fontSize: 12, marginTop: 3 },
  newActivity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    borderRadius: 11,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  newActivityText: { color: colors.white, fontWeight: '700', fontSize: 13 },
  timeline: { gap: 12 },
  empty: { padding: 24, color: colors.muted },
  emptyActivities: { color: colors.muted, fontSize: 13 },
  listState: { alignItems: 'center', gap: 8, paddingVertical: 24 },
  retryButton: {
    alignSelf: 'center',
    borderRadius: 11,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  retryText: { color: colors.white, fontWeight: '700', fontSize: 13 },
  filters: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 15,
    gap: 8,
  },
  filterLabel: { color: colors.text, fontWeight: '600', fontSize: 13, marginTop: 4 },
  authorFilter: { flexDirection: 'row', gap: 8 },
  authorInput: {
    flex: 1,
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 46,
    color: colors.text,
  },
  filterButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  pageButton: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  pageButtonDisabled: { opacity: 0.45 },
  pageButtonText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  pageLabel: { color: colors.muted, fontSize: 12 },
})
